"""Add volunteer_id and study_number to volunteers table

Revision ID: add_volunteer_fields
Revises: 20250612_initial
Create Date: 2024-07-14 20:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_volunteer_fields'
down_revision = '20250612_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('volunteer_id', sa.String(), nullable=False))
    op.add_column('volunteers', sa.Column('study_number', sa.String(), nullable=False))
    op.create_index(op.f('ix_volunteers_volunteer_id'), 'volunteers', ['volunteer_id'], unique=True)
    op.create_index(op.f('ix_volunteers_study_number'), 'volunteers', ['study_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteers_study_number'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_volunteer_id'), table_name='volunteers')
    op.drop_column('volunteers', 'study_number')
    op.drop_column('volunteers', 'volunteer_id')
    # ### end Alembic commands ###