// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pemkrfgvnzgxfjpnpitm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbWtyZmd2bnpneGZqcG5waXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Mjc2NDEsImV4cCI6MjA2NTAwMzY0MX0.21-l_z12EuoLjs3ZL-ZuJKkacHp2-DtyMBSUnJHjX_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);